name: pdf_merger_flutter
description: "A Flutter package that allows developers to easily merge multiple PDF files into a single document with a simple and intuitive API."
version: 1.0.0+4
repository: https://github.com/AliMotamedi7/pdf_merger_flutter

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  syncfusion_flutter_pdf: ^32.1.19
  file_picker: ^10.3.8
  path_provider: ^2.1.5
  open_app_file: ^4.0.4
#  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
